import json
from src.preprocess import load_config, load_processed_data
from src.models import train_lightgbm, train_xgboost
from src.evaluate import evaluate_model, compare_models, save_results, plot_roc_curves

def main():
    print("Loading config and processed data...")
    config = load_config()
    
    # Load the processed data generated by preprocess.py
    X_train_full, y_train_full, X_val, y_val, X_test, y_test = load_processed_data(config)
    
    # If the nrows limit caused empty val/test sets (temporal split failed),
    # we randomly split the training data to get a test set.
    if len(X_test) == 0:
        print("  Test set is empty (due to nrows limit during temporal split).")
        print("  Performing random split on the available data...")
        from sklearn.model_selection import train_test_split
        X_temp, X_test, y_temp, y_test = train_test_split(X_train_full, y_train_full, test_size=0.2, random_state=42)
        X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.2, random_state=42)
    else:
        X_train, y_train = X_train_full, y_train_full
    
    results = []
    roc_models = {}
    
    # 1. Train LightGBM
    print("\n--- Training LightGBM ---")
    model_lgb = train_lightgbm(X_train, y_train, config, X_val, y_val)
    
    print("\nEvaluating LightGBM on Test Set...")
    preds_lgb = model_lgb.predict_proba(X_test)[:, 1]
    res_lgb = evaluate_model("LightGBM", y_test, preds_lgb, config)
    results.append(res_lgb)
    roc_models["LightGBM"] = (y_test, preds_lgb)
    
    # 2. Train XGBoost
    print("\n--- Training XGBoost ---")
    model_xgb = train_xgboost(X_train, y_train, config, X_val, y_val)
    
    print("\nEvaluating XGBoost on Test Set...")
    preds_xgb = model_xgb.predict_proba(X_test)[:, 1]
    res_xgb = evaluate_model("XGBoost", y_test, preds_xgb, config)
    results.append(res_xgb)
    roc_models["XGBoost"] = (y_test, preds_xgb)
    
    # 3. Compare and Save
    print("\n--- Final Comparison ---")
    df_compare = compare_models(results)
    print(df_compare)
    
    save_results(results, config)
    
    # Generate all presentation visuals
    print("\nGenerating presentation visuals...")
    plot_roc_curves(roc_models, save_path="d:/credit_risk_llm/figures/roc_baselines.png")
    
    from src.evaluate import plot_pr_curves, plot_calibration_curve, plot_ks_chart
    plot_pr_curves(roc_models, save_path="d:/credit_risk_llm/figures/pr_baselines.png")
    plot_calibration_curve(roc_models, save_path="d:/credit_risk_llm/figures/calibration_baselines.png")
    
    # Plot KS Chart for XGBoost (our best model usually)
    plot_ks_chart(y_test, preds_xgb, model_name="XGBoost", save_path="d:/credit_risk_llm/figures/ks_chart_xgboost.png")
    
    # Feature Importance (LightGBM)
    import lightgbm as lgb
    import matplotlib.pyplot as plt
    plt.figure(figsize=(10, 6))
    lgb.plot_importance(model_lgb, max_num_features=15, title='Top 15 Feature Importances (LightGBM)', figsize=(10,6))
    plt.tight_layout()
    plt.savefig("d:/credit_risk_llm/figures/feature_importance_lgb.png", dpi=150)
    plt.close()

    print("Baseline evaluation complete. All visuals saved to figures/")

if __name__ == "__main__":
    main()
